name: todo
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  injectable: ^2.1.2
  logger: ^1.4.0
  freezed_annotation: ^2.2.0
  get_it: ^7.6.0
  intl: ^0.17.0
  bloc_concurrency: ^0.2.2
  dartx: ^1.1.0
  flutter_svg: ^2.0.5
  flutter_localizations:
    sdk: flutter
  envied: ^0.3.0+3
  retrofit: ^4.0.1
  retrofit_generator: ^7.0.1
  json_serializable: ^6.6.2
  dio: ^5.2.1+1
  shared_preferences: ^2.1.2
  uuid: ^3.0.7
  device_info_plus: ^9.0.2
  provider: ^6.0.5
  floor: ^1.4.2
  internet_connection_checker: ^1.0.0+1
  json_annotation: ^4.8.1

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  freezed: ^2.3.5
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  injectable_generator: ^2.1.6
  envied_generator: ^0.3.0+3
  test: ^1.22.0
  mockito: ^5.4.0
  floor_generator: ^1.4.2

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
flutter_intl:
  enabled: true
  class_name: L10n
  main_locale: ru
