name: todo
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  injectable: ^2.1.2
  logger: ^1.4.0
  freezed_annotation: ^2.2.0
  get_it: ^7.6.0
  intl: ^0.18.1
  bloc_concurrency: ^0.2.2
  dartx: ^1.1.0
  flutter_svg: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^2.3.5
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  json_serializable: ^6.6.2
  injectable_generator: ^2.1.6

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
